name: Build XMonad

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:13
    env:
      STACK_ROOT: /tmp/.stack-root

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt update
        apt install -y \
          \
          build-essential \
          curl \
          libffi-dev \
          libffi8 \
          libgmp-dev \
          libgmp10 \
          libncurses-dev \
          libncurses6 \
          libtinfo6 \
          pkg-config \
          \
          libx11-dev \
          libxft-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxss-dev

    - name: Setup Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        ghc-version: 9.2.8
        enable-stack: true
        stack-version: latest

    - name: Cache Stack dependencies
      uses: actions/cache@v3
      with:
        path: |
          /tmp/.stack-root
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml', '**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Build project
      run: |
        stack setup --allow-different-user
        stack build --copy-bins --allow-different-user

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xmonad-binaries
        path: bin/
